import './globals.css'

export const metadata = {
  title: {
    default: 'MuscleMate',
    template: '%s | MuscleMate'
  },
  robots: {
    index: true,
    follow: true,
  },

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="bg-zinc-800">{children}</body>
    </html>
  )
}
